### ISSUE TITLE
List of Requirements

### ISSUE THREAD

**Issue by mariaarieiro98** [SEAI-H-2020/Info-Management#12]

**Comment by up201605618** [comment]
@mariaarieiro98 o que precisas da parte das equipas para isto?

**Comment by mariaarieiro98** [comment]
A drive tem uma pasta para o Requirements Manual. Lá tem umas tabelas para preencher com os requisitos do cliente e dos requisitos que, dado os requisitos do cliente, nós extrapolamos para o nosso projeto. Se as sub-equipas se lembrarem de algum requisito que ainda não esteja lá era fixe irem preenchendo.
